# @req REQ-INFRA-004 Frontend service
apiVersion: v1
kind: Service
metadata:
  name: sdd-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: sdd-web
  ports:
  - port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
    nodePort: {{ .Values.web.nodePort }}
    protocol: TCP
    name: http
